= Dev Setup

The dev-Setup has different parts for Backend and frontend.

== Backend

1. Install https://github.com/borkdude/babashka[babashka].
2. Datomic in Memory database is needed.
Execute `bb run.clj datomic/run` to start datomic in memory database.
(Need to run `bb run.clj datomic/install` once before.)
3. Start the backend-server via preconfigured cursive repl or manually via `clj -A:run-server`
4. Run normal nREPL for rest.

== Frontend

The Frontend works with shadow-cljs for hot code reload.

1. Run `yarn install` or `npm install` to get javascript dependencies.
2. Run `npx shadow-cljs watch app` to compile the cljs and start the watcher.
3. Shadow-cljs starts a nrepl-server.
You can connect to localhost and the port output to the `.shadow-cljs/nrepl.port` file.
4. In the opened *CLJ* REPL you can execute `(shadow/repl :app)` to switch to the hot development REPL for *CLJS*.

=== Stylesheets

To automatically create the stylesheets, enable a file-watcher for the `public/css` directory.
In the html we use the minimized version.
So be sure to add `--style compressed` or similar as an option to your sass command.