= Dev Setup

The dev-Setup has different parts for Backend and frontend.

== Backend

1. Install https://github.com/borkdude/babashka[babashka].
2. Datomic in Memory database is needed.
Execute `bb run.clj datomic/run` to start datomic in memory database.
(Need to run `bb run.clj datomic/install` once before.)
3. Start the backend-server
a. If you need a REPL: Start "CLJ REPL" and execute the `-main` method in meetly.meeting.rest-api
b. Without REPL: `clj -A:run-server` on the terminal

== Frontend

The Frontend works with shadow-cljs for hot code reload.

1. Run `yarn install` or `npm install` to get javascript dependencies.
2. Run `npx shadow-cljs watch app` to compile the cljs and start the watcher.
3. Shadow-cljs starts a nrepl-server.
You can connect to localhost and the port output to the `.shadow-cljs/nrepl.port` file.
4. In the opened *CLJ* REPL you can execute `(shadow/repl :app)` to switch to the hot development REPL for *CLJS*.

=== Stylesheets

To automatically create the stylesheets, enable a file-watcher for the `public/css` directory.
In the html we use the minimized version.
So be sure to add `--style compressed` or similar as an option to your sass command.

== Testing To run tests locally do the following.

=== Backend

Run `clj -A:test`

=== Frontend

Run:

- `yarn shadow-cljs compile test`
- `node target/test/compiled/test.js`