= Dev Setup
:icons: font
:icon-set: fa
:source-highlighter: rouge
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:stem: latexmath
endif::[]

The dev-Setup has different parts for Backend and Frontend.

== Preparation

We are using `datomic dev-local` as our in-memory database, which can be used during development and testing.
Get the jar file containing datomic via this URL: https://docs.datomic.com/dev-local/get-dev-local.html

Then, store the jar in "local_jars/dev-local/dev-local.jar".
This database stores the data in a ".datomic/" folder.
Remove the folder to reset the database or call the suitable function in the database namespace.

== Backend

Start the backend-server with one of these two options:

*With REPL*

Start the run configuration "CLJ REPL" and execute the `-main` method in
`meetly.meeting.rest-api`.
To do this manually, you can put the following commands into the REPL in IDEA:
+
[source,clojure]
----
(require '[meetly.meeting.rest-api])
(meetly.meeting.rest-api/-main)
----

*Without REPL*

`clj -A:run-server` on the terminal

== Frontend

The Frontend works with shadow-cljs for hot code reload.

1. Run `yarn install` or `npm install` to get javascript dependencies.
2. Run `npx shadow-cljs watch app` to compile the cljs and start the watcher.
3. Shadow-cljs starts a nrepl-server.
You can connect to localhost and the port output to the `.shadow-cljs/nrepl.port` file.
4. In the opened *CLJ* REPL you can execute `(shadow/repl :app)` to switch to the hot development REPL for *CLJS*.

=== Stylesheets

To automatically create the stylesheets, enable a file-watcher for the `public/css` directory.
In the html we use the minimized version.
So be sure to add `--style compressed` or similar as an option to your sass command.

== Testing To run tests locally do the following.

=== Backend

Run `clj -A:test`

=== Frontend

Run:

- `yarn shadow-cljs compile test`
- `node target/test/compiled/test.js`