on: [push]

env:
  APP_CODE: ${{ secrets.APP_CODE }}
  CLEVERREACH_ENABLED: false
  KEYCLOAK_ADMIN_ID: ${{ secrets.KEYCLOAK_ADMIN_ID }}
  KEYCLOAK_ADMIN_SECRET: ${{ secrets.KEYCLOAK_ADMIN_SECRET }}
  KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Clojure Tests
    steps:
      - uses: actions/checkout@v3
      - id: setup-clojure
        uses: ./.github/actions/setup_clojure

      - name: Start Clojure Tests
        run: clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -M:test

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: target/coverage/lcov.info
          retention-days: 1

  test-cljs:
    runs-on: ubuntu-latest
    name: ClojureScript Tests
    steps:
      - uses: actions/checkout@v3
      - id: setup-clojure
        uses: ./.github/actions/setup_clojure
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install yarn dependencies
        run: yarn install

      - name: Start ClojureScript Tests
        run: clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -M:test-cljs
      - run: yarn karma start --single-run
