name: Setup Clojure

on: [push]

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: "temurin"
        java-version: "17"
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.1
      with:
        bb: "latest"
        cli: "latest"
        clj-kondo: "latest"

    # Optional step:
    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.deps.clj
        key: cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: cljdeps-
    - name: Copy datomic settings
      run: cp settings.xml ~/.m2/settings.xml
      shell: bash
