(ns schnaq.interface.components.icons)

(defn fa
  "Returns a fontawesome icon id as String for a given identifier"
  [identifier]
  (identifier
    {:add "fa-plus-circle"
     :arrow-down "fa-arrow-down"
     :arrow-left "fa-arrow-left"
     :arrow-right "fas fa-arrow-right"
     :arrow-up "fa-arrow-up"
     :bell "fa-bell"
     :book "fa-book"
     :calendar "fa-calendar"
     :camera "fa-camera"
     :carry "fa-people-carry"
     :check/double "fa-check-double"
     :check/normal "fas fa-check"
     :check/square "fa-check-square"
     :check/circle "fa-check-circle"
     :clipboard "fa-clipboard-list"
     :clock "fa-clock"
     :circle "fas fa-circle"
     :circle-notch "fa-circle-notch"
     :cog "fa-cog"
     :cogs "fa-cogs"
     :comment-alt "fa-comment-alt"
     :comments "fa-comments"
     :cookie/bite "fa-cookie-bite"
     :cookie/complete "fa-cookie"
     :copy "fa-copy"
     :cross "fa-times"
     :delete-icon "fa-times-circle"
     :dots "fa-ellipsis-h"
     :edit "fa-edit"
     :eraser "fa-eraser"
     :file-download "fa-file-download"
     :flag "fa-flag"
     :flask "fa-flask"
     :graph "fa-project-diagram"
     :heart "fa-heart"
     :home "fa-home"
     :info-question "fa-question-circle"
     :info "fa-info-circle"
     :language "fa-language"
     :laptop "fa-laptop-code"
     :lightbulb "fa-lightbulb"
     :lock-closed "fa-lock"
     :lock-open "fa-lock-open"
     :minus "fa-minus"
     :newspaper "fa-newspaper"
     :paragraph "fa-paragraph"
     :plane "fa-paper-plane"
     :plus "fas fa-plus"
     :project/diagram "fa-project-diagram"
     :puzzle "fa-puzzle-piece"
     :reply "fa-comment-alt"
     :rocket "fas fa-rocket"
     :search "fa-search"
     :server "fa-server"
     :share "fa-share-alt"
     :shield "fa-shield-alt"
     :site-map "fa-sitemap"
     :spinner "fa-spinner"
     :star "fas fa-star"
     :tag "fas fa-tag"
     :terminal "fa-terminal"
     :trash "fa-trash-alt"
     :user/edit "fa-user-edit"
     :user/group "fa-users"
     :user/group-edit "fa-users-cog"
     :user/lock "fa-user-lock"
     :user/ninja "fa-user-ninja"
     :user/plus "fa-user-plus"
     :user/shield "fa-user-shield"}))
