(ns schnaq.interface.components.images)

(defn img-path
  "Returns an image path as String for a given identifier"
  [identifier]
  (identifier
   {:icon-add "https://snq-common.s3.nl-ams.scw.cloud/buttons/add-button.svg"
    :icon-cards-dark "https://snq-common.s3.nl-ams.scw.cloud/icons/squares_dark.svg"
    :icon-community "https://snq-common.s3.nl-ams.scw.cloud/community.svg"
    :icon-crane "https://snq-common.s3.nl-ams.scw.cloud/icons/crane.svg"
    :icon-graph "https://snq-common.s3.nl-ams.scw.cloud/icons/mind_map_circle.svg"
    :icon-graph-dark "https://snq-common.s3.nl-ams.scw.cloud/icons/mind_map_circle_dark.svg"
    :icon-posts "https://snq-common.s3.nl-ams.scw.cloud/icons/dashboard/posts.svg"
    :icon-qanda-dark "https://snq-common.s3.nl-ams.scw.cloud/icons/qanda_dark.svg"
    :icon-reports "https://snq-common.s3.nl-ams.scw.cloud/icons/reports.svg"
    :icon-robot "https://snq-common.s3.nl-ams.scw.cloud/icons/robot.svg"
    :icon-search "https://snq-common.s3.nl-ams.scw.cloud/icons/dashboard/search.svg"
    :icon-summary "https://snq-common.s3.nl-ams.scw.cloud/icons/layers.svg"
    :icon-summary-dark "https://snq-common.s3.nl-ams.scw.cloud/icons/layers_dark.svg"
    :icon-users "https://snq-common.s3.nl-ams.scw.cloud/icons/dashboard/users.svg"
    :icon-views-dark "https://snq-common.s3.nl-ams.scw.cloud/icons/views_dark.svg"
    :icon-views-light "https://snq-common.s3.nl-ams.scw.cloud/icons/views_light.svg"
    :logo "https://snq-common.s3.nl-ams.scw.cloud/logos/schnaq.svg"
    :logo-white "https://snq-common.s3.nl-ams.scw.cloud/logos/schnaq_white.webp"
    :logo.square.schnaqqi/blue "https://snq-common.s3.nl-ams.scw.cloud/logos/schnaqqi-qr.png"
    :preview/wordcloud "https://snq-common.s3.nl-ams.scw.cloud/blurred/blurred_wordcloud.png"
    :schnaqqifant/admin "https://snq-common.s3.nl-ams.scw.cloud/schnaqqifanten/admin.png"
    :schnaqqifant/erase "https://snq-common.s3.nl-ams.scw.cloud/schnaqqifanten/erase.png"
    :schnaqqifant/share "https://snq-common.s3.nl-ams.scw.cloud/schnaqqifanten/share.png"
    :schnaqqifant/stop "https://snq-common.s3.nl-ams.scw.cloud/schnaqqifanten/stop.png"
    :schnaqqifant/talk "https://snq-common.s3.nl-ams.scw.cloud/schnaqqifanten/talk.png"
    :schnaqqifant/rocket "https://snq-common.s3.nl-ams.scw.cloud/schnaqqifanten/rocket.webp"
    :schnaqqifant/three-d-bubble "https://snq-common.s3.nl-ams.scw.cloud/schnaqqifanten/schnaqqi_bubble.png"
    :schnaqqifant/three-d-head "https://snq-common.s3.nl-ams.scw.cloud/schnaqqifanten/schnaqqi-3d-head.png"
    :schnaqqifant/three-d-left "https://snq-common.s3.nl-ams.scw.cloud/schnaqqifanten/schnaqqi-3d-head-left.png"
    :schnaqqifant/white "https://snq-common.s3.nl-ams.scw.cloud/logos/schnaqqifant_white.webp"}))
