name: Delete old container images

on:
  push:
    branches:
      - fix/cleanup
  # schedule:
  #   - cron: "0 3 * * *"

jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    steps:
      - name: Delete old containers
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: schnaq
          image-names: "*"
          image-tags: "!latest !staging" # don't delete package versions tagged with these tags
          cut-off: 4w
          keep-n-most-recent: 5
          token: ${{ secrets.PAT }}
          dry-run: true # consider toggling this to true on your first run
