name: "Vercel: Build Production Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  BUILD_HASH: ${{ github.sha }}
  KEYCLOAK_CLIENT: ${{ secrets.KEYCLOAK_CLIENT }}
  KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
  FAQ_SHARE_HASH: ${{ secrets.FAQ_SHARE_HASH }}
  REST_API_URL: ${{ vars.REST_API_URL }}

jobs:
  deploy-production:
    name: "Vercel: Build Production Deployment"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - id: setup-clojure
        uses: ./.github/actions/setup_clojure

      - name: Install Deps
        run: |
          yarn global add sass
          yarn install --frozen-lockfile

      - name: Install Vercel CLI
        run: yarn global add vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }}
