name: "Docker: Build Frontend Images"

on:
  push:
    branches:
      - deploy
      - develop
    tags:
      - v*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    environment: ${{ github.ref == 'refs/heads/develop' && 'staging' || 'production' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2
      #   with:
      #     platforms: "arm64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/deploy' }}
            type=raw,value=staging,enable={{is_default_branch}}
            type=sha

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          file: Dockerfile.frontend
          platforms: linux/amd64 #,linux/arm64
          build-args: |
            BUILD_HASH=${{ github.sha }}
            REST_API_URL=${{ vars.REST_API_URL }}
            KEYCLOAK_REALM=${{ secrets.KEYCLOAK_REALM }}
            KEYCLOAK_CLIENT=${{ secrets.KEYCLOAK_CLIENT }}
            FAQ_SHARE_HASH=${{ vars.FAQ_SHARE_HASH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
