on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: setup-clojure
        uses: ./.github/actions/setup_clojure
        env:
          DATOMIC_REPO_USERNAME: ${{ secrets.DATOMIC_REPO_USERNAME }}
          DATOMIC_REPO_PASSWORD: ${{ secrets.DATOMIC_REPO_PASSWORD }}
      - name: Execute clojure code
        run: clojure -e "(+ 1 1)"
