on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: setup-clojure
        uses: ./.github/actions/setup_clojure
      - name: Execute clojure code
        run: clojure -e "(+ 1 1)"
