on: [push]

env:
  APP_CODE: ${{ secrets.APP_CODE }}
  CLEVERREACH_ENABLED: false
  DATOMIC_REPO_USERNAME: ${{ secrets.DATOMIC_REPO_USERNAME }}
  DATOMIC_REPO_PASSWORD: ${{ secrets.DATOMIC_REPO_PASSWORD }}
  KEYCLOAK_ADMIN_ID: ${{ secrets.KEYCLOAK_ADMIN_ID }}
  KEYCLOAK_ADMIN_SECRET: ${{ secrets.KEYCLOAK_ADMIN_SECRET }}
  KEYCLOAK_REALM: ${{ secrets.KEYCLOAK_REALM }}
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_WEBHOOK_ACCESS_KEY: ${{ secrets.STRIPE_WEBHOOK_ACCESS_KEY }}
  SUMMY_URL: ${{ secrets.SUMMY_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Clojure Tests
    steps:
      - uses: actions/checkout@v3
      - id: setup-clojure
        uses: ./.github/actions/setup_clojure

      - name: Start Clojure Tests
        run: clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -A:test

  test-cljs:
    runs-on: ubuntu-latest
    name: ClojureScript Tests
    steps:
      - uses: actions/checkout@v3
      - id: setup-clojure
        uses: ./.github/actions/setup_clojure

      - name: Install yarn dependencies
        run: yarn install

      - name: Start ClojureScript Tests
        run: clojure -Sdeps '{:mvn/local-repo "./.m2/repository"}' -M:test-cljs
      - run: yarn karma start --single-run

  lint:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
      - uses: actions/checkout@v3
      # - id: setup-clojure
      #   uses: ./.github/actions/setup_clojure

      - name: Run clj-kondo
        run: clj-kondo --lint src/
